name: sehattek_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  supabase_flutter: ^2.8.4
  go_router: ^14.8.1
  sizer: ^3.0.3
  flutter_dotenv: ^5.2.1
  responsive_framework: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

assets:
  - assets/.env
  - assets/icon/checkout.png
  - assets/icon/done.png
  - assets/icon/history.png
